# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Trans.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Trans.proto',
  package='ccard.protocols.trans',
  serialized_pb='\n\x0bTrans.proto\x12\x15\x63\x63\x61rd.protocols.trans\"\x93\x06\n\x05Trans\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0f\n\x07shop_no\x18\x02 \x01(\t\x12\x11\n\tshop_name\x18\x03 \x01(\t\x12\x13\n\x0bterminal_no\x18\x04 \x01(\t\x12\x0f\n\x07\x63\x61rd_no\x18\x05 \x01(\t\x12\x13\n\x0bnew_card_no\x18\x06 \x01(\t\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x05\x12\x10\n\x08\x62\x61tch_no\x18\x08 \x01(\t\x12\x10\n\x08trace_no\x18\t \x01(\t\x12\x13\n\x0bresult_code\x18\n \x01(\t\x12\x12\n\ntrans_time\x18\x0b \x01(\t\x12\x12\n\ntrans_date\x18\x0c \x01(\t\x12\x0f\n\x07track_2\x18\r \x01(\t\x12\x18\n\x10new_card_track_2\x18\x0e \x01(\t\x12\x10\n\x08password\x18\x0f \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x10 \x01(\t\x12\x16\n\x0e\x63urrent_points\x18\x11 \x01(\t\x12\x14\n\x0ctotal_points\x18\x12 \x01(\x05\x12\x14\n\x0cold_batch_no\x18\x13 \x01(\t\x12\x14\n\x0cold_trace_no\x18\x14 \x01(\t\x12\x14\n\x0cnew_password\x18\x15 \x01(\t\x12\x16\n\x0erenew_password\x18\x16 \x01(\t\x12\x17\n\x0fmaster_password\x18\x17 \x01(\t\x12\x15\n\rpayment_count\x18\x18 \x01(\x05\x12\x16\n\x0epayment_amount\x18\x19 \x01(\x05\x12\x15\n\rdeposit_count\x18\x1a \x01(\x05\x12\x16\n\x0e\x64\x65posit_amount\x18\x1b \x01(\x05\x12\x1c\n\x14points_payment_count\x18\x1c \x01(\x05\x12\x1d\n\x15points_payment_amount\x18\x1d \x01(\x05\x12\x1c\n\x14points_deposit_count\x18\x1e \x01(\x05\x12\x1d\n\x15points_deposit_amount\x18\x1f \x01(\x05\x12\x14\n\x0coverdue_date\x18  \x01(\t\x12\x18\n\x10operator_account\x18! \x01(\t\x12\x19\n\x11operator_password\x18\" \x01(\t\x12\x11\n\tinterface\x18# \x01(\t')




_TRANS = _descriptor.Descriptor(
  name='Trans',
  full_name='ccard.protocols.trans.Trans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ccard.protocols.trans.Trans.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shop_no', full_name='ccard.protocols.trans.Trans.shop_no', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shop_name', full_name='ccard.protocols.trans.Trans.shop_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='terminal_no', full_name='ccard.protocols.trans.Trans.terminal_no', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='card_no', full_name='ccard.protocols.trans.Trans.card_no', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_card_no', full_name='ccard.protocols.trans.Trans.new_card_no', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ccard.protocols.trans.Trans.amount', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_no', full_name='ccard.protocols.trans.Trans.batch_no', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trace_no', full_name='ccard.protocols.trans.Trans.trace_no', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='ccard.protocols.trans.Trans.result_code', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trans_time', full_name='ccard.protocols.trans.Trans.trans_time', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trans_date', full_name='ccard.protocols.trans.Trans.trans_date', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_2', full_name='ccard.protocols.trans.Trans.track_2', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_card_track_2', full_name='ccard.protocols.trans.Trans.new_card_track_2', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='ccard.protocols.trans.Trans.password', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_version', full_name='ccard.protocols.trans.Trans.client_version', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_points', full_name='ccard.protocols.trans.Trans.current_points', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_points', full_name='ccard.protocols.trans.Trans.total_points', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='old_batch_no', full_name='ccard.protocols.trans.Trans.old_batch_no', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='old_trace_no', full_name='ccard.protocols.trans.Trans.old_trace_no', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_password', full_name='ccard.protocols.trans.Trans.new_password', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='renew_password', full_name='ccard.protocols.trans.Trans.renew_password', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='master_password', full_name='ccard.protocols.trans.Trans.master_password', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payment_count', full_name='ccard.protocols.trans.Trans.payment_count', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payment_amount', full_name='ccard.protocols.trans.Trans.payment_amount', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deposit_count', full_name='ccard.protocols.trans.Trans.deposit_count', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deposit_amount', full_name='ccard.protocols.trans.Trans.deposit_amount', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points_payment_count', full_name='ccard.protocols.trans.Trans.points_payment_count', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points_payment_amount', full_name='ccard.protocols.trans.Trans.points_payment_amount', index=28,
      number=29, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points_deposit_count', full_name='ccard.protocols.trans.Trans.points_deposit_count', index=29,
      number=30, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points_deposit_amount', full_name='ccard.protocols.trans.Trans.points_deposit_amount', index=30,
      number=31, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overdue_date', full_name='ccard.protocols.trans.Trans.overdue_date', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator_account', full_name='ccard.protocols.trans.Trans.operator_account', index=32,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator_password', full_name='ccard.protocols.trans.Trans.operator_password', index=33,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interface', full_name='ccard.protocols.trans.Trans.interface', index=34,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=826,
)

DESCRIPTOR.message_types_by_name['Trans'] = _TRANS

class Trans(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANS

  # @@protoc_insertion_point(class_scope:ccard.protocols.trans.Trans)


# @@protoc_insertion_point(module_scope)
